services:
  postgres:
    image: postgres:15
    container_name: skillmatch-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U skillmatch -d skillmatch" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
