# Generated by Django 5.1.5 on 2025-05-14 10:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('describe', models.TextField()),
                ('timer', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('test', models.TextField()),
                ('correct', models.TextField()),
                ('ex_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='language.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
