# Generated by Django 5.1.5 on 2025-05-14 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='uuid_user',
            field=models.ManyToManyField(related_name='exercices', to=settings.AUTH_USER_MODEL),
        ),
    ]
