# Generated by Django 5.1.5 on 2025-06-02 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0002_initial'),
        ('organisation', '0002_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='ex_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='organisation.language'),
        ),
    ]
